services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs-app-container
    ports:
      - '3000:7777'
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
