services:
  nextjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ezraamos/portfolio:latest
    container_name: nextjs-app-container
    ports:
      - '{$PORT}:7777'
    environment:
      - RESEND_API_KEY=${RESEND_API_KEY}
    restart: unless-stopped
