name: Deploy Next.js application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "RESEND_API_KEY=${{ secrets.RESEND_API_KEY }}" >> .env
      - name: Build docker image
        run: docker build -t ezraamos/portfolio .
      - name: Debug Docker Hub Username
        run: echo "Docker Hub Username ${{ secrets.DOCKER_USERNAME }}"
      - name: Debug Docker Hub Password
        run: echo "Docker Hub Password ${{ secrets.DOCKER_PASSWORD }}"
      - name: Login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Publish image to docker hub
        run: docker push ezraamos/portfolio:latest

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull ezraamos/portfolio:latest
      - name: Delete old container
        run: docker rm -f nextjs-app-container
      - name: Run docker container
        run: docker run -d -p 3000:7777 --name nextjs-app-container ezraamos/portfolio
